name: Deploy to Koyeb

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Koyeb CLI
        run: |
          curl -sSL https://install.koyeb.com | bash

      - uses: koyeb/action-git-deploy@v1
        with:
          app-name: "cruise-server"       # Update this
          service-name: "main"            # Update this
          service-env: "prod"
          git-branch: "main"
          service-ports: "3000:http"
          service-routes: "/:3000"

env:
  KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}